config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks

  root 'tasks#index'
  patch '/toggle/:id', to: 'tasks#toggle', as: :toggle
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  default_scope { order(completed: :ASC) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task_id, only: [:show, :edit, :update, :toggle, :destroy]

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to root_path
  end

  def index
    @task = Task.new
    @tasks = Task.all
  end

  def show
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to root_path
  end

  def toggle
    new_value = !@task.completed
    @task.update_attribute(:completed, new_value)
    redirect_to root_path
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :details)
  end

  def find_task_id
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title RailsTaskManager
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container.padded
      .row
        .col.m6.push-m3= yield

    = yield :after_js

app/views/tasks/_form.html.haml
- content_for :after_js do
  = javascript_tag 'textareaInit();'

#form
  = form_for(task) do |f|
    %h2 New task
    .input-field
      = f.label :name
      = f.text_field :name
    .input-field
      = f.label :details
      = f.text_area :details, class: 'materialize-textarea'
      %span.helper-text.right-align Tip: Shift + Enter to send
    .right-align= f.button fa_icon("thumb-tack"), class: 'btn-flat'

app/views/tasks/edit.html.haml
= link_to 'Go back', tasks_path, class: 'waves-effect waves-green btn-flat btn-large'
= render 'form', task: @task

app/views/tasks/index.html.haml
- content_for :after_js do
  = javascript_tag 'addTaskInit();'

%h1 Task Manager

.collection
  #add-form.collection-item{style: 'display: none'}= render 'form', task: @task
  = link_to 'Add Task', '#', class: 'add-task-item waves-effect waves-light', id: 'add-task'
  - @tasks.each do |task|
    .collection-item.avatar{class: "#{task.completed ? 'completed' : ''}"}
      = link_to(toggle_path(task), class: 'circle', style: 'display: inline-block', method: 'patch') do
        = image_tag("http://placehold.it/100/#{task.completed ? 'f2f2f2' : '4caf50'}/?text=.", alt: "")
      %span.title= task.name
      %p= task.details

      .right-align
        = link_to 'Details', task_path(task), class: 'waves-effect waves-grey btn-flat'
        = link_to 'Edit', edit_task_path(task), class: 'waves-effect waves-grey btn-flat'
        = link_to 'Delete', task_path(task), class: 'waves-effect waves-grey btn-flat', method: 'delete', data: { confirm: 'Are you sure you want to delete?' }

app/views/tasks/new.html.haml
= link_to 'Go back', tasks_path, class: 'waves-effect waves-green btn-flat btn-large'
= render 'form', task: @task

app/views/tasks/show.html.haml
#task
  = link_to 'Go back', tasks_path, class: 'waves-effect waves-green btn-flat btn-large'
  %h1= @task.name
  %p.flow-text= @task.details